# Welcome to Jekyll!
#

# Site settings
title: Alexey Yanovski
description: Developer | Marketer | Writer | Human
owner: Alexey Yanovski # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: alexey.yanovski1@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/yanovski2
  github: https://github.com/lexi89
  linkedin-square: https://linkedin.com/in/alexey-yanovski
  facebook-official: https://facebook.com/alexey.yanovski
  email: mailto:alexey.yanovski1@gmail.com

# Build settings
# highlighter: rouge
markdown: kramdown
sass:
 style: compressed
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            permalink: /webdev/:categories/:title
